### ISSUE TITLE
Add more classes for transitions

### ISSUE THREAD

**Issue by lucafalasco** [accurat/tachyons-plugin-accurat#4]
following up discussion on transitions classes: https://github.com/accurat/tachyons-extra/pull/2#pullrequestreview-104494165

**Comment by caesarsol** [comment]
I vote `transition-slow` and `transition-fast`, they should be a good start and would be ready for initial prototypes.

If the dev needs more control he can start from these classes and implement its own.

What do you think?

**Comment by caesarsol** [comment]
or `transition--slow` modifier style, but it's annoying for me to have to do `className="transition transition--slow"` every time...
